# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonparse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_value', models.FloatField()),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.AddField(
            model_name='countries',
            name='country_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonparse.Group'),
        ),
    ]
